### ISSUE TITLE
Error when trying to back up to an EU S3 bucket

### ISSUE THREAD

**Issue by dabeeeenster** [astrails/safe#26]
Steps to reproduce:

Create an s3 bucket in Europe
Attempt to back up to that bucket

Looks like it is related to this:

http://stackoverflow.com/questions/2569062/what-does-bucketalreadyownedbyyou-error-from-amazon-s3-actually-mean-i-cant-f

/usr/lib64/ruby/gems/1.8/gems/aws-s3-0.6.2/lib/aws/s3/error.rb:38:in `raise': Your previous request to create the named bucket succeeded and you already own it. (AWS::S3::BucketAlreadyOwnedByYou)
    from /usr/lib64/ruby/gems/1.8/gems/aws-s3-0.6.2/lib/aws/s3/base.rb:72:in`request'
    from /usr/lib64/ruby/gems/1.8/gems/aws-s3-0.6.2/lib/aws/s3/base.rb:88:in `put'
    from /usr/lib64/ruby/gems/1.8/gems/aws-s3-0.6.2/lib/aws/s3/bucket.rb:79:in`create'
    from /usr/lib64/ruby/gems/1.8/gems/astrails-safe-0.2.7/lib/astrails/safe/s3.rb:29:in `save'
    from /usr/lib/ruby/1.8/benchmark.rb:308:in`realtime'
    from /usr/lib64/ruby/gems/1.8/gems/astrails-safe-0.2.7/lib/astrails/safe/s3.rb:28:in `save'
    from /usr/lib64/ruby/gems/1.8/gems/astrails-safe-0.2.7/lib/astrails/safe/sink.rb:8:in`process'
    from /usr/lib64/ruby/gems/1.8/gems/astrails-safe-0.2.7/lib/astrails/safe/backup.rb:15:in `run'
    from /usr/lib64/ruby/gems/1.8/gems/astrails-safe-0.2.7/lib/astrails/safe/backup.rb:12:in`each'
    from /usr/lib64/ruby/gems/1.8/gems/astrails-safe-0.2.7/lib/astrails/safe/backup.rb:12:in `run'
    from /usr/lib64/ruby/gems/1.8/gems/astrails-safe-0.2.7/lib/astrails/safe.rb:53:in`safe'
    from /usr/lib64/ruby/gems/1.8/gems/astrails-safe-0.2.7/lib/astrails/safe/config/node.rb:51:in `each'
    from /usr/lib64/ruby/gems/1.8/gems/astrails-safe-0.2.7/lib/astrails/safe/config/node.rb:51:in`each'
    from /usr/lib64/ruby/gems/1.8/gems/astrails-safe-0.2.7/lib/astrails/safe.rb:52:in `safe'
    from /usr/lib64/ruby/gems/1.8/gems/astrails-safe-0.2.7/lib/astrails/safe.rb:46:in`each'
    from /usr/lib64/ruby/gems/1.8/gems/astrails-safe-0.2.7/lib/astrails/safe.rb:46:in `safe'
    from /home/ec2-user/backup/astrails.conf:1
    from /usr/lib64/ruby/gems/1.8/gems/astrails-safe-0.2.7/bin/astrails-safe:50:in`load'
    from /usr/lib64/ruby/gems/1.8/gems/astrails-safe-0.2.7/bin/astrails-safe:50:in `main'
    from /usr/lib64/ruby/gems/1.8/gems/astrails-safe-0.2.7/bin/astrails-safe:53
    from /usr/bin/astrails-safe:19:in`load'
    from /usr/bin/astrails-safe:19

**Comment by schorsch** [comment]
i suppose this is due to limits in the aws s3 gem, which has not been updated for a looong time. if you look at the pull requests and forks you will find the answer:
https://github.com/search?type=Everything&language=&q=aws+s3

**Comment by langalex** [comment]
[my fork](https://github.com/langalex/safe) work with eu buckets now.
