### ISSUE TITLE
Lacking net/sftp

### ISSUE THREAD

**Issue by thisgeek** [astrails/safe#7]
Can't backup since version 0.2.2:

```
/usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- net/sftp (LoadError)
from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
from /home/user/.gem/ruby/1.8/gems/astrails-safe-0.2.2/lib/astrails/safe.rb:2
from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
from /home/user/.gem/ruby/1.8/gems/astrails-safe-0.2.2/bin/astrails-safe:8
from /usr/bin/astrails-safe:19:in `load'
from /usr/bin/astrails-safe:19
```

**Comment by astrails** [comment]
thanks for reporting.
added dependency in 0.2.3
